//! Container service interface.

use boxlite_shared::{
    BoxliteError, BoxliteResult, ContainerClient, ContainerConfig as ProtoContainerConfig,
    ContainerInitRequest, container_init_response,
};
use tonic::transport::Channel;

/// Container service interface.
pub struct ContainerInterface {
    client: ContainerClient<Channel>,
}

impl ContainerInterface {
    /// Create from a channel.
    pub fn new(channel: Channel) -> Self {
        Self {
            client: ContainerClient::new(channel),
        }
    }

    /// Initialize container with configuration.
    ///
    /// # Arguments
    /// * `container_id` - Container ID (generated by host)
    /// * `config` - Image-derived container config (entrypoint, env, workdir)
    ///
    /// # Returns
    /// Container ID on success
    pub async fn init(
        &mut self,
        container_id: &str,
        config: crate::images::ContainerConfig,
    ) -> BoxliteResult<String> {
        let proto_config = ProtoContainerConfig {
            entrypoint: config.cmd.clone(),
            env: config.env.clone(),
            workdir: config.working_dir.clone(),
        };

        tracing::debug!(container_id = %container_id, "Sending ContainerInit request");
        tracing::trace!(
            container_id = %container_id,
            entrypoint = ?config.cmd,
            workdir = %config.working_dir,
            env_count = config.env.len(),
            "Container configuration"
        );

        let request = ContainerInitRequest {
            container_id: container_id.to_string(),
            container_config: Some(proto_config),
        };

        let response = self.client.init(request).await?.into_inner();

        match response.result {
            Some(container_init_response::Result::Success(success)) => {
                tracing::debug!(container_id = %success.container_id, "Container initialized");
                Ok(success.container_id)
            }
            Some(container_init_response::Result::Error(err)) => {
                tracing::error!(container_id = %container_id, "Container init failed: {}", err.reason);
                Err(BoxliteError::Internal(format!(
                    "Container init failed: {}",
                    err.reason
                )))
            }
            None => Err(BoxliteError::Internal(
                "ContainerInit response missing result".to_string(),
            )),
        }
    }
}
